services:

  # Messages Broker Redis
  redis:
    image: redis:7-alpine
    container_name: redis_broker
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "6379:6379"

  # Database
  db:
    build: 
      context: .
      dockerfile: Dockerfile.db
    container_name: recipes_db
    restart: always
    env_file: .env.local
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Main application (FastAPI)
  web:
    build: .
    image: utak3r/home-recipes:debug
    container_name: home-recipes
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "5678:5678" # debugpy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
    env_file: .env.local
    environment:
      - REDIS_URL=redis://redis:6379/0
      - TESSERACT_PATH=tesseract
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy

  # Celery worker
  worker:
    build: .
    image: utak3r/home-recipes-worker:debug
    container_name: home-recipes-worker
    command: celery -A app.workers.celery_app worker -Q ocr --loglevel=info
    ports:
      - "5679:5679" # debugpy
    healthcheck:
      test: [ "CMD", "celery", "-A", "app.workers.celery_app", "inspect", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - .:/app
    env_file: .env.local
    environment:
      - REDIS_URL=redis://redis:6379/0
      - TESSERACT_PATH=tesseract
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy

volumes:
  pgdata:
