/**
 * Dynamic environment configuration.
 * In development (Vite), it uses import.meta.env.
 * In production (Docker), it uses window._env_ generated by entrypoint.sh.
 */

interface EnvConfig {
  VITE_API_URL: string;
  VITE_GOOGLE_CLIENT_ID: string;
}

declare global {
  interface Window {
    _env_?: Partial<EnvConfig>;
  }
}

const config: EnvConfig = {
  VITE_API_URL: window._env_?.VITE_API_URL || import.meta.env.VITE_API_URL || 'http://localhost:8000',
  VITE_GOOGLE_CLIENT_ID: window._env_?.VITE_GOOGLE_CLIENT_ID || import.meta.env.VITE_GOOGLE_CLIENT_ID || '',
};

export default config;
